/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api.public.asaas-webhook'
import { Route as AuthenticatedDashboardTutorialRouteImport } from './routes/_authenticated.dashboard.tutorial'
import { Route as AuthenticatedDashboardRecuperacaoRouteImport } from './routes/_authenticated.dashboard.recuperacao'
import { Route as AuthenticatedDashboardLimparGithubRouteImport } from './routes/_authenticated.dashboard.limpar-github'
import { Route as AuthenticatedDashboardLembretesRouteImport } from './routes/_authenticated.dashboard.lembretes'
import { Route as AuthenticatedDashboardContatosRouteImport } from './routes/_authenticated.dashboard.contatos'
import { Route as AuthenticatedDashboardCampanhasRouteImport } from './routes/_authenticated.dashboard.campanhas'
import { Route as AuthenticatedDashboardAssinaturaRouteImport } from './routes/_authenticated.dashboard.assinatura'
import { Route as AuthenticatedDashboardAniversariosRouteImport } from './routes/_authenticated.dashboard.aniversarios'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated.dashboard.admin'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedAdminModelosRouteImport } from './routes/_authenticated.admin.modelos'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated.admin.logs'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated.admin.financeiro'
import { Route as AuthenticatedDashboardAssinaturaCheckoutRouteImport } from './routes/_authenticated.dashboard.assinatura.checkout'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardTutorialRoute =
  AuthenticatedDashboardTutorialRouteImport.update({
    id: '/tutorial',
    path: '/tutorial',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRecuperacaoRoute =
  AuthenticatedDashboardRecuperacaoRouteImport.update({
    id: '/recuperacao',
    path: '/recuperacao',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLimparGithubRoute =
  AuthenticatedDashboardLimparGithubRouteImport.update({
    id: '/limpar-github',
    path: '/limpar-github',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLembretesRoute =
  AuthenticatedDashboardLembretesRouteImport.update({
    id: '/lembretes',
    path: '/lembretes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContatosRoute =
  AuthenticatedDashboardContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCampanhasRoute =
  AuthenticatedDashboardCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssinaturaRoute =
  AuthenticatedDashboardAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAniversariosRoute =
  AuthenticatedDashboardAniversariosRouteImport.update({
    id: '/aniversarios',
    path: '/aniversarios',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModelosRoute =
  AuthenticatedAdminModelosRouteImport.update({
    id: '/modelos',
    path: '/modelos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardAssinaturaCheckoutRoute =
  AuthenticatedDashboardAssinaturaCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedDashboardAssinaturaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/modelos': typeof AuthenticatedAdminModelosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/aniversarios': typeof AuthenticatedDashboardAniversariosRoute
  '/dashboard/assinatura': typeof AuthenticatedDashboardAssinaturaRouteWithChildren
  '/dashboard/campanhas': typeof AuthenticatedDashboardCampanhasRoute
  '/dashboard/contatos': typeof AuthenticatedDashboardContatosRoute
  '/dashboard/lembretes': typeof AuthenticatedDashboardLembretesRoute
  '/dashboard/limpar-github': typeof AuthenticatedDashboardLimparGithubRoute
  '/dashboard/recuperacao': typeof AuthenticatedDashboardRecuperacaoRoute
  '/dashboard/tutorial': typeof AuthenticatedDashboardTutorialRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/assinatura/checkout': typeof AuthenticatedDashboardAssinaturaCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/modelos': typeof AuthenticatedAdminModelosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/aniversarios': typeof AuthenticatedDashboardAniversariosRoute
  '/dashboard/assinatura': typeof AuthenticatedDashboardAssinaturaRouteWithChildren
  '/dashboard/campanhas': typeof AuthenticatedDashboardCampanhasRoute
  '/dashboard/contatos': typeof AuthenticatedDashboardContatosRoute
  '/dashboard/lembretes': typeof AuthenticatedDashboardLembretesRoute
  '/dashboard/limpar-github': typeof AuthenticatedDashboardLimparGithubRoute
  '/dashboard/recuperacao': typeof AuthenticatedDashboardRecuperacaoRoute
  '/dashboard/tutorial': typeof AuthenticatedDashboardTutorialRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/assinatura/checkout': typeof AuthenticatedDashboardAssinaturaCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/modelos': typeof AuthenticatedAdminModelosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/aniversarios': typeof AuthenticatedDashboardAniversariosRoute
  '/_authenticated/dashboard/assinatura': typeof AuthenticatedDashboardAssinaturaRouteWithChildren
  '/_authenticated/dashboard/campanhas': typeof AuthenticatedDashboardCampanhasRoute
  '/_authenticated/dashboard/contatos': typeof AuthenticatedDashboardContatosRoute
  '/_authenticated/dashboard/lembretes': typeof AuthenticatedDashboardLembretesRoute
  '/_authenticated/dashboard/limpar-github': typeof AuthenticatedDashboardLimparGithubRoute
  '/_authenticated/dashboard/recuperacao': typeof AuthenticatedDashboardRecuperacaoRoute
  '/_authenticated/dashboard/tutorial': typeof AuthenticatedDashboardTutorialRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/assinatura/checkout': typeof AuthenticatedDashboardAssinaturaCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/admin'
    | '/dashboard'
    | '/admin/financeiro'
    | '/admin/logs'
    | '/admin/modelos'
    | '/admin/usuarios'
    | '/dashboard/admin'
    | '/dashboard/aniversarios'
    | '/dashboard/assinatura'
    | '/dashboard/campanhas'
    | '/dashboard/contatos'
    | '/dashboard/lembretes'
    | '/dashboard/limpar-github'
    | '/dashboard/recuperacao'
    | '/dashboard/tutorial'
    | '/api/public/asaas-webhook'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/assinatura/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/admin/financeiro'
    | '/admin/logs'
    | '/admin/modelos'
    | '/admin/usuarios'
    | '/dashboard/admin'
    | '/dashboard/aniversarios'
    | '/dashboard/assinatura'
    | '/dashboard/campanhas'
    | '/dashboard/contatos'
    | '/dashboard/lembretes'
    | '/dashboard/limpar-github'
    | '/dashboard/recuperacao'
    | '/dashboard/tutorial'
    | '/api/public/asaas-webhook'
    | '/admin'
    | '/dashboard'
    | '/dashboard/assinatura/checkout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/modelos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/aniversarios'
    | '/_authenticated/dashboard/assinatura'
    | '/_authenticated/dashboard/campanhas'
    | '/_authenticated/dashboard/contatos'
    | '/_authenticated/dashboard/lembretes'
    | '/_authenticated/dashboard/limpar-github'
    | '/_authenticated/dashboard/recuperacao'
    | '/_authenticated/dashboard/tutorial'
    | '/api/public/asaas-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/assinatura/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/tutorial': {
      id: '/_authenticated/dashboard/tutorial'
      path: '/tutorial'
      fullPath: '/dashboard/tutorial'
      preLoaderRoute: typeof AuthenticatedDashboardTutorialRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/recuperacao': {
      id: '/_authenticated/dashboard/recuperacao'
      path: '/recuperacao'
      fullPath: '/dashboard/recuperacao'
      preLoaderRoute: typeof AuthenticatedDashboardRecuperacaoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/limpar-github': {
      id: '/_authenticated/dashboard/limpar-github'
      path: '/limpar-github'
      fullPath: '/dashboard/limpar-github'
      preLoaderRoute: typeof AuthenticatedDashboardLimparGithubRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/lembretes': {
      id: '/_authenticated/dashboard/lembretes'
      path: '/lembretes'
      fullPath: '/dashboard/lembretes'
      preLoaderRoute: typeof AuthenticatedDashboardLembretesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/contatos': {
      id: '/_authenticated/dashboard/contatos'
      path: '/contatos'
      fullPath: '/dashboard/contatos'
      preLoaderRoute: typeof AuthenticatedDashboardContatosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/campanhas': {
      id: '/_authenticated/dashboard/campanhas'
      path: '/campanhas'
      fullPath: '/dashboard/campanhas'
      preLoaderRoute: typeof AuthenticatedDashboardCampanhasRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assinatura': {
      id: '/_authenticated/dashboard/assinatura'
      path: '/assinatura'
      fullPath: '/dashboard/assinatura'
      preLoaderRoute: typeof AuthenticatedDashboardAssinaturaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/aniversarios': {
      id: '/_authenticated/dashboard/aniversarios'
      path: '/aniversarios'
      fullPath: '/dashboard/aniversarios'
      preLoaderRoute: typeof AuthenticatedDashboardAniversariosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modelos': {
      id: '/_authenticated/admin/modelos'
      path: '/modelos'
      fullPath: '/admin/modelos'
      preLoaderRoute: typeof AuthenticatedAdminModelosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/assinatura/checkout': {
      id: '/_authenticated/dashboard/assinatura/checkout'
      path: '/checkout'
      fullPath: '/dashboard/assinatura/checkout'
      preLoaderRoute: typeof AuthenticatedDashboardAssinaturaCheckoutRouteImport
      parentRoute: typeof AuthenticatedDashboardAssinaturaRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminModelosRoute: typeof AuthenticatedAdminModelosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminModelosRoute: AuthenticatedAdminModelosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardAssinaturaRouteChildren {
  AuthenticatedDashboardAssinaturaCheckoutRoute: typeof AuthenticatedDashboardAssinaturaCheckoutRoute
}

const AuthenticatedDashboardAssinaturaRouteChildren: AuthenticatedDashboardAssinaturaRouteChildren =
  {
    AuthenticatedDashboardAssinaturaCheckoutRoute:
      AuthenticatedDashboardAssinaturaCheckoutRoute,
  }

const AuthenticatedDashboardAssinaturaRouteWithChildren =
  AuthenticatedDashboardAssinaturaRoute._addFileChildren(
    AuthenticatedDashboardAssinaturaRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAniversariosRoute: typeof AuthenticatedDashboardAniversariosRoute
  AuthenticatedDashboardAssinaturaRoute: typeof AuthenticatedDashboardAssinaturaRouteWithChildren
  AuthenticatedDashboardCampanhasRoute: typeof AuthenticatedDashboardCampanhasRoute
  AuthenticatedDashboardContatosRoute: typeof AuthenticatedDashboardContatosRoute
  AuthenticatedDashboardLembretesRoute: typeof AuthenticatedDashboardLembretesRoute
  AuthenticatedDashboardLimparGithubRoute: typeof AuthenticatedDashboardLimparGithubRoute
  AuthenticatedDashboardRecuperacaoRoute: typeof AuthenticatedDashboardRecuperacaoRoute
  AuthenticatedDashboardTutorialRoute: typeof AuthenticatedDashboardTutorialRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardAniversariosRoute:
      AuthenticatedDashboardAniversariosRoute,
    AuthenticatedDashboardAssinaturaRoute:
      AuthenticatedDashboardAssinaturaRouteWithChildren,
    AuthenticatedDashboardCampanhasRoute: AuthenticatedDashboardCampanhasRoute,
    AuthenticatedDashboardContatosRoute: AuthenticatedDashboardContatosRoute,
    AuthenticatedDashboardLembretesRoute: AuthenticatedDashboardLembretesRoute,
    AuthenticatedDashboardLimparGithubRoute:
      AuthenticatedDashboardLimparGithubRoute,
    AuthenticatedDashboardRecuperacaoRoute:
      AuthenticatedDashboardRecuperacaoRoute,
    AuthenticatedDashboardTutorialRoute: AuthenticatedDashboardTutorialRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
